---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: voter
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./voter
  prune: true
  sourceRef:
    kind: GitRepository
    name: voter
    namespace: flux-system
  targetNamespace: default

